Repository ankitgoyal0106/Swap-Shop, pull requests merged in 2024-12, with the labels that each got.

#108 Model Factory Creation
  back-end/src/model/ModelFactory.js
Labels: enhancement

#115 Complete implementation of item repository service in the front end.
  front-end/src/components/itemPage/createItemPage.js
  front-end/src/eventhub/Events.js
  front-end/src/main.js
  front-end/src/services/ItemRepoFactory.js
  front-end/src/services/ItemRepoRemoteService.js
  front-end/src/services/ItemRepoService.js
Labels: enhancement

#125 Item Page Rendering
  front-end/src/components/AppController/AppController.js
  front-end/src/components/itemPage/itemPage.js
  front-end/src/eventhub/Events.js
  front-end/src/index.html
Labels: enhancement

#137 Item Creation SQLite
  back-end/node_modules/.package-lock.json
  back-end/package-lock.json
  back-end/src/auth/middleware.js
  back-end/src/controller/ItemController.js
  back-end/src/database.sqlite
  back-end/src/model/InMemoryItemModel.js
  back-end/src/model/ModelFactory.js
  back-end/src/model/SQLiteItemModel.js
  back-end/src/routes/Routes.js
  back-end/src/server.js
  front-end/src/components/itemPage/createItemPage.js
  front-end/src/services/ItemRepoFactory.js
  front-end/src/services/ItemRepoRemoteService.js
  front-end/src/testPage.html
  package-lock.json
  package.json
Labels: enhancement

#164 Recently Viewed on Explore Page Working
  back-end/src/database.sqlite
  front-end/src/components/explorePage/explorePage.js
  front-end/src/components/itemPage/createItemPage.js
Labels: enhancement

#165 Milestone 4 Documentation!!
  front-end/src/.DS_Store
  front-end/src/achievement-badges/.DS_Store
  team/m2/roles.md
  team/reports/nathan-palmer.md
Labels: documentation

#170 160 display user items in profile
  back-end/src/controller/ChatController.js
  back-end/src/controller/ItemController.js
  back-end/src/controller/ProfileController.js
  back-end/src/model/SQLiteItemModel.js
  back-end/src/routes/Routes.js
  front-end/src/components/AppController/AppController.js
  front-end/src/components/ProfileController/ProfileController.js
  front-end/src/components/ViewProfile/ViewProfile.css
  front-end/src/components/ViewProfile/ViewProfile.js
  front-end/src/components/itemPage/createItemPage.js
  front-end/src/components/registrationPage/registrationPage.js
  front-end/src/eventhub/Events.js
  front-end/src/services/ItemRepoRemoteService.js
Labels: bug, enhancement

#172 Milestone 4 Documentation for Scott Puopolo
  README.md
  team/m2/roles.md
  team/reports/scott-puopolo.md
Labels: documentation
